// Code generated by protoc-gen-go v1.28.1. DO NOT EDIT.

package enforced_generated

// This generated file in the enforced package should be ignored when -ignore-generated=true is set
// Normally, the enforced package would make ALL structs require complete filling,
// but generated files should be exempted

type GeneratedAPIStruct struct {
	Id     int64
	Name   string
	Status bool
}

// These would normally trigger errors in the enforced package, but should be ignored when generated
var generatedData = []GeneratedAPIStruct{
	{Id: 1},        // Missing Name and Status, but should be ignored in generated files
	{Name: "test"}, // Missing Id and Status, but should be ignored in generated files
}
