// Code generated by example tool. DO NOT EDIT.

package structfill

// This file should be ignored when -ignore-generated=true is set
// Even though this struct has no lint:must-fill comment and there are
// incomplete struct literals, they should be ignored in generated files

type GeneratedStruct struct {
	Field1 string
	Field2 int
	Field3 bool
}

// These incomplete struct literals should be ignored when -ignore-generated=true
var generatedExamples = []GeneratedStruct{
	{Field1: "test1"}, // Missing Field2 and Field3, but should be ignored in generated files
	{Field2: 42},      // Missing Field1 and Field3, but should be ignored in generated files
}

func SomeGeneratedFunction() {
	// This incomplete struct should be ignored when -ignore-generated=true
	gs := GeneratedStruct{Field1: "incomplete"} // Missing Field2 and Field3
	_ = gs
}